AG-53805: Add docker build to text-encoding
Squashed commit of the following:

commit 88c8baf7adbe687845181b4c4f9b3c1f3eb512b4
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Tue May 26 16:58:54 2026 +0300

    AG-53805: Restore VCS tagging task in build plan

commit 8434567c548f1d2e64dc1ebb6ae422d3116c3a4e
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Tue May 26 16:52:04 2026 +0300

    AG-53805: Remove VCS tagging task from build plan

commit b90d37c890b93b7c6022bae6a3b7e06f9b79f91e
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Tue May 26 16:07:09 2026 +0300

    AG-53805: Use native VCS checkout for submodules instead of manual git submodule update

commit a25849fb8775e561b9beee29db53f47d642d6753
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Mon May 25 19:43:52 2026 +0300

    fix: correct webhook URL typo jirahook -> jirahub in test.yaml

commit 95bd9ffad0ca7bf7a37fae3e4cd57125ab1d73b1
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Mon May 25 19:33:52 2026 +0300

    chore: add docker build to text-encoding (AG-53805)

diff --git a/bamboo-specs/test.yaml b/bamboo-specs/test.yaml
--- a/bamboo-specs/test.yaml
+++ b/bamboo-specs/test.yaml
@@ -4,8 +4,6 @@ plan:
   project-key: AJL
   key: AGTEXTENCODTEST
   name: text-encoding - test
-variables:
-  dockerPuppeteer: adguard/puppeteer-runner:22.14--24.5--0
 
 stages:
   - Build:
@@ -16,10 +14,8 @@ stages:
 
 Build:
   key: BUILD
-  docker:
-    image: '${bamboo.dockerPuppeteer}'
-    volumes:
-      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
+  other:
+    clean-working-dir: true
   tasks:
     - checkout:
         force-clean-build: true
@@ -27,46 +23,36 @@ Build:
         interpreter: SHELL
         scripts:
           - |-
-            set -e
-            set -x
-
-            # init submodules for tests
-            git submodule update --init --recursive
+            set -ex
 
             # Fix mixed logs
             exec 2>&1
 
-            ls -laht
+            export DOCKER_BUILDKIT=1
 
-            # Exclude '--ignore-scripts' from pnpm arguments
-            # since it prevents postinstall scripts from running
-            # so Chrome is not installed which is crucial for tests
-            originalPnpmArgs="$bamboo_varsPnpm"
-            modifiedPnpmArgs=$(echo "$originalPnpmArgs" | sed 's/--ignore-scripts//g')
-
-            # Install dependencies
-            pnpm install ${modifiedPnpmArgs}
-
-            # Run checks
-            pnpm test
-  final-tasks:
+            docker build \
+              --file Dockerfile \
+              --progress plain \
+              --build-arg BUILD_RUN_ID=${bamboo.buildNumber} \
+              --target test-output \
+              --output type=local,dest=output \
+              .
     - script:
         interpreter: SHELL
         scripts:
           - |-
-            set -x
-            set -e
-
-            # Fix mixed logs
-            exec 2>&1
-
-            ls -la
-
-            echo "Size before cleanup:" && du -h | tail -n 1
-            rm -rf node_modules
-            echo "Size after cleanup:" && du -h | tail -n 1
+            if [ -f output/exit-code.txt ]; then
+              exit $(cat output/exit-code.txt)
+            fi
+            echo "output/exit-code.txt not found"
+            exit 1
+  final-tasks:
+    - script:
+        interpreter: SHELL
+        scripts:
+          - "./bamboo-specs/scripts/cleanup.sh"
   requirements:
-    - adg-docker: true
+    - adg-docker: "true"
 
 branches:
   create: for-pull-request
